// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAat6U1ZDxKBvdxL4HVc4FRttew-g_8e8k',
    appId: '1:558099384615:web:ce824a84ae3c2295650102',
    messagingSenderId: '558099384615',
    projectId: 'cinema-review-e2e82',
    authDomain: 'cinema-review-e2e82.firebaseapp.com',
    storageBucket: 'cinema-review-e2e82.appspot.com',
    measurementId: 'G-HBHWDSKK9K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1d4l4dl_uA8aimegMX_EE9tBWTp2lTDo',
    appId: '1:558099384615:android:342af7767223ca9b650102',
    messagingSenderId: '558099384615',
    projectId: 'cinema-review-e2e82',
    storageBucket: 'cinema-review-e2e82.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP3VS9tBoiAQwdM5L_5-PjBKfhB8h7F_Q',
    appId: '1:558099384615:ios:24a392b2d224830f650102',
    messagingSenderId: '558099384615',
    projectId: 'cinema-review-e2e82',
    storageBucket: 'cinema-review-e2e82.appspot.com',
    iosBundleId: 'com.example.cinemaReview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP3VS9tBoiAQwdM5L_5-PjBKfhB8h7F_Q',
    appId: '1:558099384615:ios:17dc6660bccbdd9d650102',
    messagingSenderId: '558099384615',
    projectId: 'cinema-review-e2e82',
    storageBucket: 'cinema-review-e2e82.appspot.com',
    iosBundleId: 'com.example.cinemaReview.RunnerTests',
  );
}
